version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - NODE_ENV=qua
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:



# REORGANISATION
  # CENTRALISER LES FICHIER DE CONFIGURATION
  # INTEGRE
  # PURIFIER LE REPO 
  # ESSAYER DE FAIRE UN TRUC PROPRE POUR QUE SA REPRESENTE UNE TEMPLATE DE DEMARAGE
# FIX DE BDD